name: Patch and Build

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: ./gradlew build
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            **/Folia-Server/build/libs/folia-server-1.20.1-R0.1-SNAPSHOT.jar
            **/build/libs/folia-1.20.1-R0.1-SNAPSHOT.jar

